version: '3'

services:
  producer:
    container_name: producer
    image: producer:latest
    # build:
    #   context: .
    #   dockerfile: producer/Dockerfile
    depends_on:
      - kafka
    restart: on-failure
    ports:
      - "6061:6061"
    networks:
      - kafka-network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - kafka-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # Use the container name as the advertised host name
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - kafka-network

networks:
  kafka-network:
    external: true
